"""
Adaptive hybrid with tighter opens and lower bluff variance.

Generated by sandbox/build_bot.py from strategy_components.
This file is standalone and intentionally does not import local project modules.
"""
import json
import os
import random

import eval7

BOT_NAME = "Adaptive Hybrid v5 Filtered GTO Preflop"
CONFIG = {'equity_iterations': 85, 'open_late': 52, 'open_middle': 58, 'open_early': 64, 'continue_late': 62, 'continue_early': 70, 'premium_pair_rank': 10, 'value_equity': 0.61, 'raise_equity': 0.73, 'call_margin': 0.055, 'multiway_margin': 0.038, 'late_bluff_frequency': 0.18, 'steal_adjustment': 4, 'aggro_tighten': 5, 'short_stack_enabled': True, 'short_stack_bb': 18, 'short_stack_jam_score': 69, 'short_stack_call_score': 74, 'postflop_draw_raise_frequency': 0.18, 'value_bet_fraction': 0.64, 'pressure_bet_fraction': 0.48, 'raise_bet_fraction': 0.88, 'river_extra_margin': 0.045, 'large_bet_extra_margin': 0.075, 'danger_extra_margin': 0.025}
RANK_VALUE = {rank: value for value, rank in enumerate("23456789TJQKA", 2)}
BIG_BLIND = 100



# ---------------------------------------------------------------------------
# GTO preflop table hook for 6-max tables. Postflop remains this bot's own
# strategy; this only overrides preflop spots covered by data/preflop_ranges.json.
# ---------------------------------------------------------------------------
GTO_RANKS = "23456789TJQKA"
GTO_RANK_VALUE = {rank: value for value, rank in enumerate(GTO_RANKS, 2)}
GTO_DATA_DIR = os.environ.get("BOT_DATA_DIR", os.path.join(os.path.dirname(__file__), "data"))
GTO_PREFLOP_PATH = os.path.join(GTO_DATA_DIR, "preflop_ranges.json")


def _gto_load_preflop_table():
    try:
        with open(GTO_PREFLOP_PATH, "r", encoding="utf-8") as handle:
            return json.load(handle)
    except Exception:
        return {"rfi": {}, "vs_rfi": {}, "vs_limp": {}}


GTO_PREFLOP_TABLE = _gto_load_preflop_table()


def _gto_preflop_features(cards):
    high, low = sorted((GTO_RANK_VALUE[card[0]] for card in cards), reverse=True)
    suited = cards[0][1] == cards[1][1]
    pair = high == low
    gap = high - low
    return high, low, suited, pair, gap


def _gto_hand_code(cards):
    high, low, suited, pair, _gap = _gto_preflop_features(cards)
    hi = GTO_RANKS[high - 2]
    lo = GTO_RANKS[low - 2]
    if pair:
        return hi + lo
    return hi + lo + ("s" if suited else "o")


def _gto_rank_index(rank):
    return GTO_RANKS.index(rank)


def _gto_all_hand_codes():
    hands = set()
    for i in range(len(GTO_RANKS) - 1, -1, -1):
        for j in range(i, -1, -1):
            if i == j:
                hands.add(GTO_RANKS[i] + GTO_RANKS[j])
            else:
                hands.add(GTO_RANKS[i] + GTO_RANKS[j] + "s")
                hands.add(GTO_RANKS[i] + GTO_RANKS[j] + "o")
    return hands


def _gto_expand_pair(token):
    if "-" in token:
        start, end = token.split("-")
        hi = _gto_rank_index(start[0])
        lo = _gto_rank_index(end[0])
    else:
        hi = _gto_rank_index(token[0])
        lo = hi
    if token.endswith("+"):
        lo = hi
        hi = len(GTO_RANKS) - 1
    lo, hi = min(lo, hi), max(lo, hi)
    return {GTO_RANKS[i] + GTO_RANKS[i] for i in range(lo, hi + 1)}


def _gto_expand_non_pair(token):
    suitedness = token[-1]
    body = token[:-1]
    high = body[0]
    low = body[1]
    high_idx = _gto_rank_index(high)
    low_idx = _gto_rank_index(low)
    if token.endswith("+"):
        suitedness = token[-2]
        high = token[0]
        low = token[1]
        high_idx = _gto_rank_index(high)
        low_idx = _gto_rank_index(low)
        return {high + GTO_RANKS[i] + suitedness for i in range(low_idx, high_idx)}
    if "-" in token:
        start, end = token.split("-")
        suitedness = start[-1]
        high = start[0]
        start_low = _gto_rank_index(start[1])
        end_low = _gto_rank_index(end[1])
        start_low, end_low = min(start_low, end_low), max(start_low, end_low)
        return {high + GTO_RANKS[i] + suitedness for i in range(start_low, end_low + 1)}
    return {token}


def _gto_expand_range(tokens):
    hands = set()
    for token in tokens:
        token = token.strip()
        if not token:
            continue
        if token == "ALL":
            hands.update(_gto_all_hand_codes())
        elif len(token) >= 2 and token[0] == token[1]:
            hands.update(_gto_expand_pair(token))
        else:
            hands.update(_gto_expand_non_pair(token))
    return hands


def _gto_position_label(state):
    pos = state["seat_to_act"] / max(1, len(state.get("players", [])) - 1)
    if pos >= 0.67:
        return "late"
    if pos >= 0.34:
        return "middle"
    return "early"


def _gto_position_from_blinds(state):
    players = state.get("players", [])
    n = len(players)
    if n < 2:
        return "BTN"
    sb = bb = None
    for item in state.get("action_log", [])[:4]:
        if item.get("action") == "small_blind":
            sb = item.get("seat")
        elif item.get("action") == "big_blind":
            bb = item.get("seat")
    if sb is None or bb is None:
        return _gto_position_label(state).upper()
    offsets = {
        (bb + 1) % n: "LJ",
        (bb + 2) % n: "HJ",
        (bb + 3) % n: "CO",
        (bb + 4) % n: "BTN",
        sb: "SB",
        bb: "BB",
    }
    return offsets.get(state["seat_to_act"], _gto_position_label(state).upper())


def _gto_first_rfi_position(state):
    players = state.get("players", [])
    n = len(players)
    if n < 2:
        return None
    sb = bb = None
    for item in state.get("action_log", [])[:4]:
        if item.get("action") == "small_blind":
            sb = item.get("seat")
        elif item.get("action") == "big_blind":
            bb = item.get("seat")
    if sb is None or bb is None:
        return None
    seat_to_pos = {
        (bb + 1) % n: "LJ",
        (bb + 2) % n: "HJ",
        (bb + 3) % n: "CO",
        (bb + 4) % n: "BTN",
        sb: "SB",
        bb: "BB",
    }
    for item in state.get("action_log", [])[2:]:
        if item.get("action") in ("raise", "all_in"):
            return seat_to_pos.get(item.get("seat"))
        if item.get("action") == "call" and item.get("seat") == sb:
            return "SB"
    return None


def _gto_raise_to_bb(state, bb_amount):
    cap = state["your_stack"] + state["your_bet_this_street"]
    amount = int(bb_amount * BIG_BLIND)
    return min(max(state["min_raise_to"], amount), cap)


def _gto_frequency_action(spot, code):
    for item in spot.get("frequencies", []):
        if code not in _gto_expand_range(item.get("hands", [])):
            continue
        roll = random.random()
        cumulative = 0.0
        for action in ("raise", "call", "check", "fold"):
            cumulative += float(item.get(action, 0.0))
            if roll <= cumulative:
                return action
        return "fold"
    return None


def _gto_table_action_from_name(state, action_name, spot, position):
    if action_name == "raise":
        if state["current_bet"] <= BIG_BLIND:
            return {"action": "raise", "amount": _gto_raise_to_bb(state, spot.get("raise_size_bb", 2.5))}
        multiplier = spot.get("raise_multiplier", 3.5 if position not in ("SB", "BB") else 4.0)
        amount = int(state["current_bet"] * multiplier)
        return {"action": "raise", "amount": min(state["your_stack"] + state["your_bet_this_street"], max(state["min_raise_to"], amount))}
    if action_name == "call":
        if state["amount_owed"]:
            return {"action": "call"}
        if state["can_check"]:
            return {"action": "check"}
    if action_name == "check" and state["can_check"]:
        return {"action": "check"}
    if state["can_check"]:
        return {"action": "check"}
    return {"action": "fold"}


def _gto_table_preflop_action(state):
    if len(state.get("players", [])) != 6 or state.get("street") != "preflop":
        return None
    code = _gto_hand_code(state["your_cards"])
    position = _gto_position_from_blinds(state)
    opener = _gto_first_rfi_position(state)

    if opener is None and state["current_bet"] <= BIG_BLIND:
        spot = GTO_PREFLOP_TABLE.get("rfi", {}).get(position)
        if not spot:
            return None
        action_name = _gto_frequency_action(spot, code)
        if action_name:
            return _gto_table_action_from_name(state, action_name, spot, position)
        if code in _gto_expand_range(spot.get("raise", [])):
            return {"action": "raise", "amount": _gto_raise_to_bb(state, spot.get("raise_size_bb", 2.5))}
        if state["amount_owed"] and code in _gto_expand_range(spot.get("call", [])):
            return {"action": "call"}
        if state["can_check"]:
            return {"action": "check"}
        return {"action": "fold"}

    if opener == "SB" and position == "BB" and state["can_check"]:
        spot = GTO_PREFLOP_TABLE.get("vs_limp", {}).get("BB_vs_SB")
        if not spot:
            return None
        action_name = _gto_frequency_action(spot, code)
        if action_name:
            return _gto_table_action_from_name(state, action_name, spot, position)
        return {"action": "check"}

    if opener and opener != position and state["amount_owed"]:
        spot = GTO_PREFLOP_TABLE.get("vs_rfi", {}).get(position + "_vs_" + opener)
        if not spot:
            return None
        action_name = _gto_frequency_action(spot, code)
        if action_name:
            if action_name == "call" and state["amount_owed"] > state["your_stack"] * 0.28:
                return {"action": "fold"}
            return _gto_table_action_from_name(state, action_name, spot, position)
        if code in _gto_expand_range(spot.get("raise", [])):
            multiplier = spot.get("raise_multiplier", 3.5 if position not in ("SB", "BB") else 4.0)
            amount = int(state["current_bet"] * multiplier)
            return {"action": "raise", "amount": min(state["your_stack"] + state["your_bet_this_street"], max(state["min_raise_to"], amount))}
        if code in _gto_expand_range(spot.get("call", [])) and state["amount_owed"] <= state["your_stack"] * 0.28:
            return {"action": "call"}
        return {"action": "fold"}
    return None

def _cards(cards):
    return [eval7.Card(card) for card in cards]


def _position_factor(state):
    return state["seat_to_act"] / max(1, len(state["players"]) - 1)


def _position_label(state):
    pos = _position_factor(state)
    if pos >= 0.67:
        return "late"
    if pos >= 0.34:
        return "middle"
    return "early"


def _live_opponents(state):
    me = state["seat_to_act"]
    return sum(1 for p in state["players"] if p["seat"] != me and not p["is_folded"] and p["state"] != "busted")


def _profile_table(state):
    recent = state.get("match_action_log", [])[-300:]
    count = max(1, len(recent))
    raises = sum(1 for action in recent if action.get("action") in ("raise", "all_in"))
    folds = sum(1 for action in recent if action.get("action") == "fold")
    calls = sum(1 for action in recent if action.get("action") == "call")
    raise_rate = raises / count
    fold_rate = folds / count
    call_rate = calls / count
    if raise_rate > 0.24:
        label = "aggressive"
    elif fold_rate > 0.34:
        label = "foldy"
    elif call_rate > 0.34:
        label = "sticky"
    else:
        label = "balanced"
    return {"raise_rate": raise_rate, "fold_rate": fold_rate, "call_rate": call_rate, "label": label}


def _hand_features(cards):
    high, low = sorted((RANK_VALUE[card[0]] for card in cards), reverse=True)
    suited = cards[0][1] == cards[1][1]
    pair = high == low
    gap = high - low
    return high, low, suited, pair, gap


def _preflop_score(cards):
    high, low, suited, pair, gap = _hand_features(cards)
    if pair:
        return 58 + high * 3
    broadway = int(high >= 10) + int(low >= 10)
    return high * 3 + low * 1.5 + broadway * 3 + (8 if high == 14 else 0) + (5 if suited else 0) - max(0, gap - 2) * 2


def _board_texture(state):
    board = state["community_cards"]
    all_cards = board + state["your_cards"]
    ranks = [card[0] for card in all_cards]
    suits = [card[1] for card in all_cards]
    values = sorted(set(RANK_VALUE[card[0]] for card in all_cards))
    flush_draw = len(board) >= 3 and any(suits.count(suit) >= 4 for suit in "shdc")
    straight_draw = len(board) >= 3 and any(len([v for v in values if start <= v <= start + 4]) >= 4 for start in range(2, 11))
    paired_board = len(board) >= 3 and len(set(card[0] for card in board)) < len(board)
    has_pair = any(ranks.count(card[0]) >= 2 for card in state["your_cards"])
    board_suits = [card[1] for card in board]
    board_values = sorted(set(RANK_VALUE[card[0]] for card in board))
    board_danger = len(board) >= 3 and (
        any(board_suits.count(suit) >= 3 for suit in "shdc")
        or any(len([v for v in board_values if start <= v <= start + 4]) >= 3 for start in range(2, 11))
    )
    wet = flush_draw or straight_draw or board_danger
    return {"flush_draw": flush_draw, "straight_draw": straight_draw, "paired_board": paired_board, "has_pair": has_pair, "wet": wet, "board_danger": board_danger}


def _street_aggression(state):
    return sum(1 for action in state["action_log"] if action.get("action") in ("raise", "all_in"))


def _stack_mode(state):
    bb = state["your_stack"] / BIG_BLIND
    if bb <= CONFIG["short_stack_bb"]:
        mode = "short"
    elif bb >= 80:
        mode = "deep"
    else:
        mode = "normal"
    spr = state["your_stack"] / max(1, state["pot"])
    return {"bb": bb, "mode": mode, "spr": spr}


def _pot_price(state):
    owed = state["amount_owed"]
    pot = max(1, state["pot"])
    price = owed / (pot + owed) if owed else 0.0
    if owed == 0:
        label = "free"
    elif owed <= pot * 0.18:
        label = "cheap"
    elif owed <= pot * 0.45:
        label = "medium"
    else:
        label = "expensive"
    return {"price": price, "label": label}


def _equity(state, opponents):
    hole = _cards(state["your_cards"])
    board = _cards(state["community_cards"])
    used = set(hole + board)
    deck = [card for card in eval7.Deck() if card not in used]
    need = 5 - len(board)
    wins = 0
    ties = 0
    iterations = CONFIG["equity_iterations"]
    for _ in range(iterations):
        random.shuffle(deck)
        runout = deck[:need]
        idx = need
        hero = eval7.evaluate(hole + board + runout)
        tied = False
        lost = False
        for _opp in range(opponents):
            villain = eval7.evaluate([deck[idx], deck[idx + 1]] + board + runout)
            idx += 2
            if villain > hero:
                lost = True
                break
            if villain == hero:
                tied = True
        if not lost:
            if tied:
                ties += 1
            else:
                wins += 1
    return (wins + 0.5 * ties) / iterations


def _bet_to(state, pot_fraction):
    cap = state["your_stack"] + state["your_bet_this_street"]
    raise_to = max(state["min_raise_to"], int(max(100, state["pot"]) * pot_fraction))
    return min(raise_to, cap)


def extract_features(state):
    opponents = max(1, _live_opponents(state))
    stack = _stack_mode(state)
    profile = _profile_table(state)
    texture = _board_texture(state)
    hand_score = _preflop_score(state["your_cards"])
    equity = None if state["street"] == "preflop" else _equity(state, opponents)
    return {
        "opponents": opponents,
        "position": _position_label(state),
        "position_factor": _position_factor(state),
        "stack": stack,
        "profile": profile,
        "texture": texture,
        "hand_score": hand_score,
        "hand_features": _hand_features(state["your_cards"]),
        "pot_price": _pot_price(state),
        "street_aggression": _street_aggression(state),
        "equity": equity,
    }


def short_stack_policy_applies(features):
    return CONFIG["short_stack_enabled"] and features["stack"]["mode"] == "short"


def short_stack_action(state, features):
    owed = state["amount_owed"]
    score = features["hand_score"]
    if score >= CONFIG["short_stack_jam_score"]:
        return {"action": "all_in"}
    if owed and score >= CONFIG["short_stack_call_score"] and owed <= state["your_stack"] * 0.35:
        return {"action": "call"}
    if state["can_check"]:
        return {"action": "check"}
    return {"action": "fold"}


def preflop_policy(state, features):
    owed = state["amount_owed"]
    pot = max(1, state["pot"])
    score = features["hand_score"]
    high, low, suited, pair, gap = features["hand_features"]
    profile = features["profile"]
    position = features["position"]
    cap = state["your_stack"] + state["your_bet_this_street"]
    unopened = state["current_bet"] <= BIG_BLIND

    premium = pair and high >= CONFIG["premium_pair_rank"]
    premium = premium or high == 14 and low >= 12
    premium = premium or suited and high >= 13 and low >= 12

    if position == "late":
        open_line = CONFIG["open_late"]
        continue_line = CONFIG["continue_late"]
    elif position == "middle":
        open_line = CONFIG["open_middle"]
        continue_line = (CONFIG["continue_late"] + CONFIG["continue_early"]) / 2
    else:
        open_line = CONFIG["open_early"]
        continue_line = CONFIG["continue_early"]

    if profile["label"] == "foldy" and position == "late":
        open_line -= CONFIG["steal_adjustment"]
    if profile["label"] == "aggressive":
        open_line += CONFIG["aggro_tighten"]
        continue_line += CONFIG["aggro_tighten"] * 0.6
    if features["opponents"] >= 5:
        open_line += 3

    if premium:
        multiplier = 4.0 if profile["label"] == "aggressive" else 3.2
        size = max(state["min_raise_to"], int(max(state["current_bet"], BIG_BLIND) * multiplier), int(pot * 1.0))
        return {"action": "raise", "amount": min(size, cap)}
    if unopened and score >= open_line:
        fraction = 1.0 if position == "late" else 1.35
        return {"action": "raise", "amount": _bet_to(state, fraction)}
    speculative = pair or suited and gap <= 3 and high >= 9
    if owed and score >= continue_line and owed <= pot * (0.32 if profile["label"] != "aggressive" else 0.22):
        return {"action": "call"}
    if owed and speculative and owed <= pot * 0.16:
        return {"action": "call"}
    if state["can_check"]:
        return {"action": "check"}
    return {"action": "fold"}


def _native_preflop_lines(features):
    position = features["position"]
    profile = features["profile"]
    if position == "late":
        open_line = CONFIG["open_late"]
        continue_line = CONFIG["continue_late"]
    elif position == "middle":
        open_line = CONFIG["open_middle"]
        continue_line = (CONFIG["continue_late"] + CONFIG["continue_early"]) / 2
    else:
        open_line = CONFIG["open_early"]
        continue_line = CONFIG["continue_early"]
    if profile["label"] == "foldy" and position == "late":
        open_line -= CONFIG["steal_adjustment"]
    if profile["label"] == "aggressive":
        open_line += CONFIG["aggro_tighten"]
        continue_line += CONFIG["aggro_tighten"] * 0.6
    if features["opponents"] >= 5:
        open_line += 3
    return open_line, continue_line


def _premium_preflop(features):
    high, low, suited, pair, _gap = features["hand_features"]
    premium = pair and high >= CONFIG["premium_pair_rank"]
    premium = premium or high == 14 and low >= 12
    premium = premium or suited and high >= 13 and low >= 12
    monster = pair and high >= 12 or high == 14 and low >= 13
    return premium, monster


def filtered_gto_preflop_action(state, features):
    table_action = _gto_table_preflop_action(state)
    if not table_action:
        return None
    action = table_action.get("action")
    if action in ("fold", "check"):
        return table_action

    score = features["hand_score"]
    open_line, continue_line = _native_preflop_lines(features)
    premium, monster = _premium_preflop(features)
    owed = state["amount_owed"]
    pot = max(1, state["pot"])
    stack = max(1, state["your_stack"])
    commit = 0
    if action == "raise":
        commit = max(0, int(table_action.get("amount") or 0) - state["your_bet_this_street"])
    elif action == "call":
        commit = owed

    # Let GTO widen unopened opens, but not with hands the native bot considers
    # far below range or when the raise would commit too much of the stack.
    if state["current_bet"] <= BIG_BLIND:
        if action == "raise" and score >= open_line - 5 and commit <= stack * 0.26:
            return table_action
        if action == "call" and owed <= pot * 0.18 and score >= continue_line - 8:
            return table_action
        return None

    # Versus raises, use GTO only as a disciplined range guide. The tournament
    # engine punishes speculative preflop continues that create low-SPR stackoffs.
    if action == "call":
        if premium and owed <= stack * 0.34:
            return table_action
        if score >= continue_line - 2 and owed <= pot * 0.24 and owed <= stack * 0.22:
            return table_action
        return None
    if action == "raise":
        if monster:
            return table_action
        if premium and score >= continue_line + 5 and commit <= stack * 0.30:
            return table_action
        return None
    return None


def postflop_policy(state, features):
    owed = state["amount_owed"]
    pot = max(1, state["pot"])
    equity = features["equity"]
    profile = features["profile"]
    texture = features["texture"]
    price = features["pot_price"]["price"]
    position = features["position"]
    opponents = features["opponents"]
    margin = CONFIG["call_margin"] + CONFIG["multiway_margin"] * max(0, opponents - 1)
    if profile["label"] == "aggressive":
        margin += CONFIG["aggro_tighten"] / 100.0
    if texture["wet"] and opponents >= 3:
        margin += 0.025
    if texture["board_danger"] and not texture["has_pair"]:
        margin += CONFIG["danger_extra_margin"]
    if state["street"] == "river" and not texture["has_pair"]:
        margin += CONFIG["river_extra_margin"]
    if owed > state["your_stack"] * 0.34:
        margin += CONFIG["large_bet_extra_margin"]

    if owed == 0:
        if equity >= CONFIG["value_equity"] or texture["has_pair"] and equity >= 0.50:
            return {"action": "raise", "amount": _bet_to(state, CONFIG["value_bet_fraction"])}
        can_pressure = position == "late" and opponents <= 2 and features["street_aggression"] == 0
        if can_pressure and (texture["flush_draw"] or texture["straight_draw"] or equity >= 0.42):
            if random.random() < CONFIG["late_bluff_frequency"]:
                return {"action": "raise", "amount": _bet_to(state, CONFIG["pressure_bet_fraction"])}
        return {"action": "check"}

    if equity >= CONFIG["raise_equity"] + 0.03 and owed <= state["your_stack"] * 0.38:
        return {"action": "raise", "amount": _bet_to(state, CONFIG["raise_bet_fraction"])}
    if (texture["flush_draw"] or texture["straight_draw"]) and position == "late" and owed <= pot * 0.20:
        if random.random() < CONFIG["postflop_draw_raise_frequency"]:
            return {"action": "raise", "amount": _bet_to(state, CONFIG["pressure_bet_fraction"])}
    if equity >= price + margin:
        return {"action": "call"}
    return {"action": "fold"}


def decide(state):
    features = extract_features(state)
    if short_stack_policy_applies(features):
        return short_stack_action(state, features)
    if state["street"] == "preflop":
        table_preflop_action = filtered_gto_preflop_action(state, features)
        if table_preflop_action:
            return table_preflop_action
        return preflop_policy(state, features)
    return postflop_policy(state, features)
