"""Strategy profiles used by sandbox/build_bot.py."""

STRATEGIES = {
    "equity_position": {
        "bot_name": "Equity Position v1",
        "description": "Equity guard core with position-aware opens and c-bets.",
        "equity_iterations": 85,
        "open_late": 48,
        "open_middle": 54,
        "open_early": 60,
        "continue_late": 58,
        "continue_early": 66,
        "premium_pair_rank": 10,
        "value_equity": 0.58,
        "raise_equity": 0.70,
        "call_margin": 0.045,
        "multiway_margin": 0.035,
        "late_bluff_frequency": 0.30,
        "steal_adjustment": 0,
        "aggro_tighten": 0,
        "short_stack_enabled": False,
        "short_stack_bb": 14,
        "short_stack_jam_score": 69,
        "short_stack_call_score": 74,
        "postflop_draw_raise_frequency": 0.25,
        "value_bet_fraction": 0.62,
        "pressure_bet_fraction": 0.50,
        "raise_bet_fraction": 0.85,
    },
    "anti_aggro": {
        "bot_name": "Anti Aggro v1",
        "description": "Tight trap/value strategy versus high raise-rate tables.",
        "equity_iterations": 80,
        "open_late": 54,
        "open_middle": 60,
        "open_early": 66,
        "continue_late": 64,
        "continue_early": 72,
        "premium_pair_rank": 9,
        "value_equity": 0.64,
        "raise_equity": 0.76,
        "call_margin": 0.060,
        "multiway_margin": 0.045,
        "late_bluff_frequency": 0.12,
        "steal_adjustment": 2,
        "aggro_tighten": 7,
        "short_stack_enabled": False,
        "short_stack_bb": 14,
        "short_stack_jam_score": 72,
        "short_stack_call_score": 76,
        "postflop_draw_raise_frequency": 0.12,
        "value_bet_fraction": 0.72,
        "pressure_bet_fraction": 0.42,
        "raise_bet_fraction": 0.95,
    },
    "short_stack_survivor": {
        "bot_name": "Short Stack Survivor v1",
        "description": "Conservative baseline with short-stack jam/fold override.",
        "equity_iterations": 75,
        "open_late": 52,
        "open_middle": 58,
        "open_early": 64,
        "continue_late": 64,
        "continue_early": 72,
        "premium_pair_rank": 10,
        "value_equity": 0.62,
        "raise_equity": 0.74,
        "call_margin": 0.055,
        "multiway_margin": 0.040,
        "late_bluff_frequency": 0.16,
        "steal_adjustment": 1,
        "aggro_tighten": 4,
        "short_stack_enabled": True,
        "short_stack_bb": 18,
        "short_stack_jam_score": 66,
        "short_stack_call_score": 72,
        "postflop_draw_raise_frequency": 0.15,
        "value_bet_fraction": 0.60,
        "pressure_bet_fraction": 0.42,
        "raise_bet_fraction": 0.82,
    },
    "adaptive_hybrid": {
        "bot_name": "Adaptive Hybrid v1",
        "description": "Hand equity, position, opponent profile, and stack mode.",
        "equity_iterations": 85,
        "open_late": 50,
        "open_middle": 56,
        "open_early": 62,
        "continue_late": 60,
        "continue_early": 68,
        "premium_pair_rank": 10,
        "value_equity": 0.60,
        "raise_equity": 0.72,
        "call_margin": 0.050,
        "multiway_margin": 0.038,
        "late_bluff_frequency": 0.24,
        "steal_adjustment": 4,
        "aggro_tighten": 5,
        "short_stack_enabled": True,
        "short_stack_bb": 15,
        "short_stack_jam_score": 68,
        "short_stack_call_score": 74,
        "postflop_draw_raise_frequency": 0.22,
        "value_bet_fraction": 0.64,
        "pressure_bet_fraction": 0.48,
        "raise_bet_fraction": 0.88,
    },
}


VERSION_OVERRIDES = {
    "adaptive_hybrid": {
        "v2": {
            "bot_name": "Adaptive Hybrid v2",
            "description": "Adaptive hybrid with tighter opens and lower bluff variance.",
            "open_late": 52,
            "open_middle": 58,
            "open_early": 64,
            "continue_late": 62,
            "continue_early": 70,
            "value_equity": 0.61,
            "raise_equity": 0.73,
            "call_margin": 0.055,
            "late_bluff_frequency": 0.18,
            "postflop_draw_raise_frequency": 0.18,
            "short_stack_bb": 18,
            "short_stack_jam_score": 69,
        },
    },
}
