"""Standalone bot template emitted by sandbox/build_bot.py."""

BOT_TEMPLATE = '''"""
{description}

Generated by sandbox/build_bot.py from strategy_components.
This file is standalone and intentionally does not import local project modules.
"""
import random

import eval7

BOT_NAME = {bot_name!r}
CONFIG = {config}
RANK_VALUE = {{rank: value for value, rank in enumerate("23456789TJQKA", 2)}}
BIG_BLIND = 100


def _cards(cards):
    return [eval7.Card(card) for card in cards]


def _position_factor(state):
    return state["seat_to_act"] / max(1, len(state["players"]) - 1)


def _position_label(state):
    pos = _position_factor(state)
    if pos >= 0.67:
        return "late"
    if pos >= 0.34:
        return "middle"
    return "early"


def _live_opponents(state):
    me = state["seat_to_act"]
    return sum(1 for p in state["players"] if p["seat"] != me and not p["is_folded"] and p["state"] != "busted")


def _profile_table(state):
    recent = state.get("match_action_log", [])[-300:]
    count = max(1, len(recent))
    raises = sum(1 for action in recent if action.get("action") in ("raise", "all_in"))
    folds = sum(1 for action in recent if action.get("action") == "fold")
    calls = sum(1 for action in recent if action.get("action") == "call")
    raise_rate = raises / count
    fold_rate = folds / count
    call_rate = calls / count
    if raise_rate > 0.24:
        label = "aggressive"
    elif fold_rate > 0.34:
        label = "foldy"
    elif call_rate > 0.34:
        label = "sticky"
    else:
        label = "balanced"
    return {{"raise_rate": raise_rate, "fold_rate": fold_rate, "call_rate": call_rate, "label": label}}


def _hand_features(cards):
    high, low = sorted((RANK_VALUE[card[0]] for card in cards), reverse=True)
    suited = cards[0][1] == cards[1][1]
    pair = high == low
    gap = high - low
    return high, low, suited, pair, gap


def _preflop_score(cards):
    high, low, suited, pair, gap = _hand_features(cards)
    if pair:
        return 58 + high * 3
    broadway = int(high >= 10) + int(low >= 10)
    return high * 3 + low * 1.5 + broadway * 3 + (8 if high == 14 else 0) + (5 if suited else 0) - max(0, gap - 2) * 2


def _board_texture(state):
    board = state["community_cards"]
    all_cards = board + state["your_cards"]
    ranks = [card[0] for card in all_cards]
    suits = [card[1] for card in all_cards]
    values = sorted(set(RANK_VALUE[card[0]] for card in all_cards))
    flush_draw = len(board) >= 3 and any(suits.count(suit) >= 4 for suit in "shdc")
    straight_draw = len(board) >= 3 and any(len([v for v in values if start <= v <= start + 4]) >= 4 for start in range(2, 11))
    paired_board = len(board) >= 3 and len(set(card[0] for card in board)) < len(board)
    has_pair = any(ranks.count(card[0]) >= 2 for card in state["your_cards"])
    wet = flush_draw or straight_draw
    return {{"flush_draw": flush_draw, "straight_draw": straight_draw, "paired_board": paired_board, "has_pair": has_pair, "wet": wet}}


def _street_aggression(state):
    return sum(1 for action in state["action_log"] if action.get("action") in ("raise", "all_in"))


def _stack_mode(state):
    bb = state["your_stack"] / BIG_BLIND
    if bb <= CONFIG["short_stack_bb"]:
        mode = "short"
    elif bb >= 80:
        mode = "deep"
    else:
        mode = "normal"
    spr = state["your_stack"] / max(1, state["pot"])
    return {{"bb": bb, "mode": mode, "spr": spr}}


def _pot_price(state):
    owed = state["amount_owed"]
    pot = max(1, state["pot"])
    price = owed / (pot + owed) if owed else 0.0
    if owed == 0:
        label = "free"
    elif owed <= pot * 0.18:
        label = "cheap"
    elif owed <= pot * 0.45:
        label = "medium"
    else:
        label = "expensive"
    return {{"price": price, "label": label}}


def _equity(state, opponents):
    hole = _cards(state["your_cards"])
    board = _cards(state["community_cards"])
    used = set(hole + board)
    deck = [card for card in eval7.Deck() if card not in used]
    need = 5 - len(board)
    wins = 0
    ties = 0
    iterations = CONFIG["equity_iterations"]
    for _ in range(iterations):
        random.shuffle(deck)
        runout = deck[:need]
        idx = need
        hero = eval7.evaluate(hole + board + runout)
        tied = False
        lost = False
        for _opp in range(opponents):
            villain = eval7.evaluate([deck[idx], deck[idx + 1]] + board + runout)
            idx += 2
            if villain > hero:
                lost = True
                break
            if villain == hero:
                tied = True
        if not lost:
            if tied:
                ties += 1
            else:
                wins += 1
    return (wins + 0.5 * ties) / iterations


def _bet_to(state, pot_fraction):
    cap = state["your_stack"] + state["your_bet_this_street"]
    raise_to = max(state["min_raise_to"], int(max(100, state["pot"]) * pot_fraction))
    return min(raise_to, cap)


def extract_features(state):
    opponents = max(1, _live_opponents(state))
    stack = _stack_mode(state)
    profile = _profile_table(state)
    texture = _board_texture(state)
    hand_score = _preflop_score(state["your_cards"])
    equity = None if state["street"] == "preflop" else _equity(state, opponents)
    return {{
        "opponents": opponents,
        "position": _position_label(state),
        "position_factor": _position_factor(state),
        "stack": stack,
        "profile": profile,
        "texture": texture,
        "hand_score": hand_score,
        "hand_features": _hand_features(state["your_cards"]),
        "pot_price": _pot_price(state),
        "street_aggression": _street_aggression(state),
        "equity": equity,
    }}


def short_stack_policy_applies(features):
    return CONFIG["short_stack_enabled"] and features["stack"]["mode"] == "short"


def short_stack_action(state, features):
    owed = state["amount_owed"]
    score = features["hand_score"]
    if score >= CONFIG["short_stack_jam_score"]:
        return {{"action": "all_in"}}
    if owed and score >= CONFIG["short_stack_call_score"] and owed <= state["your_stack"] * 0.35:
        return {{"action": "call"}}
    if state["can_check"]:
        return {{"action": "check"}}
    return {{"action": "fold"}}


def preflop_policy(state, features):
    owed = state["amount_owed"]
    pot = max(1, state["pot"])
    score = features["hand_score"]
    high, low, suited, pair, gap = features["hand_features"]
    profile = features["profile"]
    position = features["position"]
    cap = state["your_stack"] + state["your_bet_this_street"]
    unopened = state["current_bet"] <= BIG_BLIND

    premium = pair and high >= CONFIG["premium_pair_rank"]
    premium = premium or high == 14 and low >= 12
    premium = premium or suited and high >= 13 and low >= 12

    if position == "late":
        open_line = CONFIG["open_late"]
        continue_line = CONFIG["continue_late"]
    elif position == "middle":
        open_line = CONFIG["open_middle"]
        continue_line = (CONFIG["continue_late"] + CONFIG["continue_early"]) / 2
    else:
        open_line = CONFIG["open_early"]
        continue_line = CONFIG["continue_early"]

    if profile["label"] == "foldy" and position == "late":
        open_line -= CONFIG["steal_adjustment"]
    if profile["label"] == "aggressive":
        open_line += CONFIG["aggro_tighten"]
        continue_line += CONFIG["aggro_tighten"] * 0.6
    if features["opponents"] >= 5:
        open_line += 3

    if premium:
        multiplier = 4.0 if profile["label"] == "aggressive" else 3.2
        size = max(state["min_raise_to"], int(max(state["current_bet"], BIG_BLIND) * multiplier), int(pot * 1.0))
        return {{"action": "raise", "amount": min(size, cap)}}
    if unopened and score >= open_line:
        fraction = 1.0 if position == "late" else 1.35
        return {{"action": "raise", "amount": _bet_to(state, fraction)}}
    speculative = pair or suited and gap <= 3 and high >= 9
    if owed and score >= continue_line and owed <= pot * (0.32 if profile["label"] != "aggressive" else 0.22):
        return {{"action": "call"}}
    if owed and speculative and owed <= pot * 0.16:
        return {{"action": "call"}}
    if state["can_check"]:
        return {{"action": "check"}}
    return {{"action": "fold"}}


def postflop_policy(state, features):
    owed = state["amount_owed"]
    pot = max(1, state["pot"])
    equity = features["equity"]
    profile = features["profile"]
    texture = features["texture"]
    price = features["pot_price"]["price"]
    position = features["position"]
    opponents = features["opponents"]
    margin = CONFIG["call_margin"] + CONFIG["multiway_margin"] * max(0, opponents - 1)
    if profile["label"] == "aggressive":
        margin += CONFIG["aggro_tighten"] / 100.0
    if texture["wet"] and opponents >= 3:
        margin += 0.025

    if owed == 0:
        if equity >= CONFIG["value_equity"] or texture["has_pair"] and equity >= 0.50:
            return {{"action": "raise", "amount": _bet_to(state, CONFIG["value_bet_fraction"])}}
        can_pressure = position == "late" and opponents <= 2 and features["street_aggression"] == 0
        if can_pressure and (texture["flush_draw"] or texture["straight_draw"] or equity >= 0.42):
            if random.random() < CONFIG["late_bluff_frequency"]:
                return {{"action": "raise", "amount": _bet_to(state, CONFIG["pressure_bet_fraction"])}}
        return {{"action": "check"}}

    if equity >= CONFIG["raise_equity"] and owed <= state["your_stack"] * 0.50:
        return {{"action": "raise", "amount": _bet_to(state, CONFIG["raise_bet_fraction"])}}
    if (texture["flush_draw"] or texture["straight_draw"]) and position == "late" and owed <= pot * 0.20:
        if random.random() < CONFIG["postflop_draw_raise_frequency"]:
            return {{"action": "raise", "amount": _bet_to(state, CONFIG["pressure_bet_fraction"])}}
    if equity >= price + margin:
        return {{"action": "call"}}
    return {{"action": "fold"}}


def decide(state):
    features = extract_features(state)
    if short_stack_policy_applies(features):
        return short_stack_action(state, features)
    if state["street"] == "preflop":
        return preflop_policy(state, features)
    return postflop_policy(state, features)
'''
