"""
Adaptive hybrid with tighter opens and lower bluff variance.

Generated by sandbox/build_bot.py from strategy_components.
This file is standalone and intentionally does not import local project modules.
"""
import random

import eval7

BOT_NAME = 'Adaptive Hybrid v3-2'
CONFIG = {'equity_iterations': 85, 'open_late': 48, 'open_middle': 56, 'open_early': 63, 'continue_late': 57, 'continue_early': 65, 'premium_pair_rank': 10, 'value_equity': 0.61, 'raise_equity': 0.73, 'call_margin': 0.055, 'cheap_call_margin_discount': 0.055, 'multiway_margin': 0.038, 'late_bluff_frequency': 0.18, 'steal_adjustment': 6, 'aggro_tighten': 5, 'short_stack_enabled': True, 'short_stack_bb': 18, 'micro_stack_bb': 8, 'medium_stack_bb': 35, 'short_stack_jam_score': 70, 'micro_stack_jam_score': 64, 'short_stack_call_score': 74, 'cheap_short_call_score': 55, 'medium_short_call_score': 63, 'call_off_score': 77, 'postflop_draw_raise_frequency': 0.18, 'value_bet_fraction': 0.64, 'pressure_bet_fraction': 0.48, 'raise_bet_fraction': 0.88, 'river_extra_margin': 0.045, 'large_bet_extra_margin': 0.075, 'danger_extra_margin': 0.025, 'model_min_actions': 16}
RANK_VALUE = {rank: value for value, rank in enumerate("23456789TJQKA", 2)}
BIG_BLIND = 100


def _cards(cards):
    return [eval7.Card(card) for card in cards]


def _position_factor(state):
    return state["seat_to_act"] / max(1, len(state["players"]) - 1)


def _position_label(state):
    pos = _position_factor(state)
    if pos >= 0.67:
        return "late"
    if pos >= 0.34:
        return "middle"
    return "early"


def _live_opponents(state):
    me = state["seat_to_act"]
    return sum(1 for p in state["players"] if p["seat"] != me and not p["is_folded"] and p["state"] != "busted")


def _hero_bot_id(state):
    seat = state["seat_to_act"]
    for player in state["players"]:
        if player["seat"] == seat:
            return player.get("bot_id")
    return None


def _live_opp_ids(state):
    seat = state["seat_to_act"]
    ids = []
    for player in state["players"]:
        if player["seat"] == seat or player.get("is_folded") or player.get("state") == "busted":
            continue
        ids.append(player.get("bot_id"))
    return [bot_id for bot_id in ids if bot_id]


def _build_opponent_model(state):
    hero = _hero_bot_id(state)
    acc = {}
    seen_hand = set()
    for entry in state.get("match_action_log", [])[-300:]:
        bot_id = entry.get("bot_id")
        if not bot_id or bot_id == hero:
            continue
        action = entry.get("action")
        stats = acc.setdefault(bot_id, {"hands": 0, "vpip": 0, "pfr": 0, "decisions": 0, "raises": 0, "calls": 0, "folds": 0, "allins": 0})
        hand_key = (entry.get("hand_num"), bot_id)
        if hand_key not in seen_hand:
            seen_hand.add(hand_key)
            stats["hands"] += 1
            if action in ("call", "raise", "all_in"):
                stats["vpip"] += 1
            if action in ("raise", "all_in"):
                stats["pfr"] += 1
        stats["decisions"] += 1
        if action == "raise":
            stats["raises"] += 1
        elif action == "call":
            stats["calls"] += 1
        elif action == "fold":
            stats["folds"] += 1
        elif action == "all_in":
            stats["allins"] += 1

    model = {}
    for bot_id, stats in acc.items():
        hands = max(1, stats["hands"])
        decisions = max(1, stats["decisions"])
        vpip = stats["vpip"] / hands
        pfr = stats["pfr"] / hands
        aggression = (stats["raises"] + stats["allins"]) / max(1, stats["calls"])
        fold_freq = stats["folds"] / decisions
        allin_freq = stats["allins"] / decisions
        model[bot_id] = {
            "actions": stats["decisions"],
            "vpip": vpip,
            "pfr": pfr,
            "aggression": aggression,
            "fold_freq": fold_freq,
            "allin_freq": allin_freq,
            "archetype": _opponent_archetype(stats["decisions"], vpip, aggression, fold_freq, allin_freq),
        }
    return model


def _opponent_archetype(actions, vpip, aggression, fold_freq, allin_freq):
    if actions < CONFIG["model_min_actions"]:
        return "unknown"
    if vpip <= 0.24 and fold_freq >= 0.55:
        return "nit"
    if allin_freq >= 0.10 or (vpip >= 0.40 and aggression >= 2.0) or (vpip >= 0.55 and aggression >= 1.3):
        return "maniac"
    if aggression <= 0.5 and vpip >= 0.25:
        return "station"
    return "tag"


def _model_profile(model, bot_id):
    return model.get(bot_id, {"actions": 0, "vpip": 0.32, "pfr": 0.18, "aggression": 1.2, "fold_freq": 0.45, "allin_freq": 0.0, "archetype": "unknown"})


def _live_archetypes(state, model):
    return [_model_profile(model, bot_id)["archetype"] for bot_id in _live_opp_ids(state)]


def _last_aggressor_id(state):
    hero_seat = state["seat_to_act"]
    for action in reversed(state.get("action_log", [])):
        if action.get("seat") == hero_seat:
            continue
        if action.get("action") in ("raise", "all_in"):
            return action.get("bot_id")
    return None


def _steal_bonus_from_model(state, model):
    ids = _live_opp_ids(state)
    if not ids:
        return 0
    fold_freq = 1.0
    for bot_id in ids:
        profile = _model_profile(model, bot_id)
        if profile["archetype"] in ("unknown", "station", "maniac"):
            return 0
        fold_freq = min(fold_freq, profile["fold_freq"])
    return int(max(0, min(5, round((fold_freq - 0.45) * 12))))


def _fold_equity_from_model(state, model):
    ids = _live_opp_ids(state)
    if not ids:
        return 0.45
    fold_equity = 1.0
    for bot_id in ids:
        profile = _model_profile(model, bot_id)
        archetype = profile["archetype"]
        if archetype == "station":
            fold_equity = min(fold_equity, 0.05)
        elif archetype == "maniac":
            fold_equity = min(fold_equity, 0.15)
        elif archetype == "unknown":
            fold_equity = min(fold_equity, 0.45)
        else:
            fold_equity = min(fold_equity, max(0.0, min(0.90, profile["fold_freq"])))
    return fold_equity


def _profile_table(state):
    recent = state.get("match_action_log", [])[-300:]
    count = max(1, len(recent))
    raises = sum(1 for action in recent if action.get("action") in ("raise", "all_in"))
    folds = sum(1 for action in recent if action.get("action") == "fold")
    calls = sum(1 for action in recent if action.get("action") == "call")
    raise_rate = raises / count
    fold_rate = folds / count
    call_rate = calls / count
    if raise_rate > 0.24:
        label = "aggressive"
    elif fold_rate > 0.34:
        label = "foldy"
    elif call_rate > 0.34:
        label = "sticky"
    else:
        label = "balanced"
    return {"raise_rate": raise_rate, "fold_rate": fold_rate, "call_rate": call_rate, "label": label}


def _hand_features(cards):
    high, low = sorted((RANK_VALUE[card[0]] for card in cards), reverse=True)
    suited = cards[0][1] == cards[1][1]
    pair = high == low
    gap = high - low
    return high, low, suited, pair, gap


def _preflop_score(cards):
    high, low, suited, pair, gap = _hand_features(cards)
    if pair:
        return 58 + high * 3
    broadway = int(high >= 10) + int(low >= 10)
    return high * 3 + low * 1.5 + broadway * 3 + (8 if high == 14 else 0) + (5 if suited else 0) - max(0, gap - 2) * 2


def _board_texture(state):
    board = state["community_cards"]
    all_cards = board + state["your_cards"]
    ranks = [card[0] for card in all_cards]
    suits = [card[1] for card in all_cards]
    values = sorted(set(RANK_VALUE[card[0]] for card in all_cards))
    flush_draw = len(board) >= 3 and any(suits.count(suit) >= 4 for suit in "shdc")
    straight_draw = len(board) >= 3 and any(len([v for v in values if start <= v <= start + 4]) >= 4 for start in range(2, 11))
    paired_board = len(board) >= 3 and len(set(card[0] for card in board)) < len(board)
    has_pair = any(ranks.count(card[0]) >= 2 for card in state["your_cards"])
    board_suits = [card[1] for card in board]
    board_values = sorted(set(RANK_VALUE[card[0]] for card in board))
    board_danger = len(board) >= 3 and (
        any(board_suits.count(suit) >= 3 for suit in "shdc")
        or any(len([v for v in board_values if start <= v <= start + 4]) >= 3 for start in range(2, 11))
    )
    wet = flush_draw or straight_draw or board_danger
    return {"flush_draw": flush_draw, "straight_draw": straight_draw, "paired_board": paired_board, "has_pair": has_pair, "wet": wet, "board_danger": board_danger}


def _street_aggression(state):
    return sum(1 for action in state["action_log"] if action.get("action") in ("raise", "all_in"))


def _stack_mode(state):
    bb = state["your_stack"] / BIG_BLIND
    if bb <= CONFIG["micro_stack_bb"]:
        mode = "micro"
    elif bb <= CONFIG["short_stack_bb"]:
        mode = "short"
    elif bb <= CONFIG["medium_stack_bb"]:
        mode = "medium"
    elif bb >= 80:
        mode = "deep"
    else:
        mode = "normal"
    spr = state["your_stack"] / max(1, state["pot"])
    return {"bb": bb, "mode": mode, "spr": spr}


def _pot_price(state):
    owed = state["amount_owed"]
    pot = max(1, state["pot"])
    price = owed / (pot + owed) if owed else 0.0
    if owed == 0:
        label = "free"
    elif owed <= pot * 0.18:
        label = "cheap"
    elif owed <= pot * 0.45:
        label = "medium"
    else:
        label = "expensive"
    return {"price": price, "label": label}


def _equity(state, opponents):
    hole = _cards(state["your_cards"])
    board = _cards(state["community_cards"])
    used = set(hole + board)
    deck = [card for card in eval7.Deck() if card not in used]
    need = 5 - len(board)
    wins = 0
    ties = 0
    iterations = CONFIG["equity_iterations"]
    for _ in range(iterations):
        random.shuffle(deck)
        runout = deck[:need]
        idx = need
        hero = eval7.evaluate(hole + board + runout)
        tied = False
        lost = False
        for _opp in range(opponents):
            villain = eval7.evaluate([deck[idx], deck[idx + 1]] + board + runout)
            idx += 2
            if villain > hero:
                lost = True
                break
            if villain == hero:
                tied = True
        if not lost:
            if tied:
                ties += 1
            else:
                wins += 1
    return (wins + 0.5 * ties) / iterations


def _bet_to(state, pot_fraction):
    cap = state["your_stack"] + state["your_bet_this_street"]
    raise_to = max(state["min_raise_to"], int(max(100, state["pot"]) * pot_fraction))
    return min(raise_to, cap)


def extract_features(state):
    opponents = max(1, _live_opponents(state))
    stack = _stack_mode(state)
    profile = _profile_table(state)
    model = _build_opponent_model(state)
    texture = _board_texture(state)
    hand_score = _preflop_score(state["your_cards"])
    equity = None if state["street"] == "preflop" else _equity(state, opponents)
    return {
        "opponents": opponents,
        "position": _position_label(state),
        "position_factor": _position_factor(state),
        "stack": stack,
        "profile": profile,
        "model": model,
        "live_archetypes": _live_archetypes(state, model),
        "bettor_archetype": _model_profile(model, _last_aggressor_id(state))["archetype"],
        "fold_equity": _fold_equity_from_model(state, model),
        "texture": texture,
        "hand_score": hand_score,
        "hand_features": _hand_features(state["your_cards"]),
        "pot_price": _pot_price(state),
        "street_aggression": _street_aggression(state),
        "equity": equity,
    }


def short_stack_policy_applies(features):
    return CONFIG["short_stack_enabled"] and features["stack"]["mode"] in ("micro", "short")


def short_stack_action(state, features):
    owed = state["amount_owed"]
    pot = max(1, state["pot"])
    score = features["hand_score"]
    mode = features["stack"]["mode"]
    high, low, suited, pair, gap = features["hand_features"]
    premium = pair and high >= CONFIG["premium_pair_rank"]
    premium = premium or high == 14 and low >= 12
    premium = premium or suited and high >= 13 and low >= 12
    cheap_price = owed and owed <= pot * 0.36
    medium_price = owed and owed <= pot * 0.48 and owed <= state["your_stack"] * 0.42

    if mode == "micro":
        if owed and (premium or score >= CONFIG["call_off_score"] or cheap_price and score >= CONFIG["cheap_short_call_score"]):
            return {"action": "call"}
        if state["street"] == "preflop" and score >= CONFIG["micro_stack_jam_score"]:
            return {"action": "all_in"}
        if state["can_check"]:
            return {"action": "check"}
        return {"action": "fold"}

    if owed and premium and owed <= state["your_stack"] * 0.45:
        return {"action": "call"}
    if owed and cheap_price and score >= CONFIG["cheap_short_call_score"]:
        return {"action": "call"}
    if owed and medium_price and score >= CONFIG["medium_short_call_score"]:
        return {"action": "call"}
    if owed and score >= CONFIG["call_off_score"] and owed <= state["your_stack"] * 0.55:
        return {"action": "call"}
    if state["street"] == "preflop" and (premium or score >= CONFIG["short_stack_jam_score"]):
        return {"action": "all_in"}
    if state["can_check"]:
        return {"action": "check"}
    return {"action": "fold"}


def preflop_policy(state, features):
    owed = state["amount_owed"]
    pot = max(1, state["pot"])
    score = features["hand_score"]
    high, low, suited, pair, gap = features["hand_features"]
    profile = features["profile"]
    position = features["position"]
    cap = state["your_stack"] + state["your_bet_this_street"]
    unopened = state["current_bet"] <= BIG_BLIND

    premium = pair and high >= CONFIG["premium_pair_rank"]
    premium = premium or high == 14 and low >= 12
    premium = premium or suited and high >= 13 and low >= 12

    if position == "late":
        open_line = CONFIG["open_late"]
        continue_line = CONFIG["continue_late"]
    elif position == "middle":
        open_line = CONFIG["open_middle"]
        continue_line = (CONFIG["continue_late"] + CONFIG["continue_early"]) / 2
    else:
        open_line = CONFIG["open_early"]
        continue_line = CONFIG["continue_early"]

    if profile["label"] == "foldy" and position == "late":
        open_line -= CONFIG["steal_adjustment"]
    if position == "late":
        open_line -= _steal_bonus_from_model(state, features["model"])
    if profile["label"] == "aggressive":
        open_line += CONFIG["aggro_tighten"]
        continue_line += CONFIG["aggro_tighten"] * 0.6
    if features["opponents"] >= 5:
        open_line += 3
    if features["stack"]["mode"] == "normal" and position == "late" and profile["label"] != "aggressive":
        open_line -= 2

    if premium:
        multiplier = 4.0 if profile["label"] == "aggressive" else 3.2
        size = max(state["min_raise_to"], int(max(state["current_bet"], BIG_BLIND) * multiplier), int(pot * 1.0))
        return {"action": "raise", "amount": min(size, cap)}
    if unopened and score >= open_line:
        fraction = 1.0 if position == "late" else 1.35
        return {"action": "raise", "amount": _bet_to(state, fraction)}
    speculative = pair or suited and gap <= 3 and high >= 9
    if features["stack"]["mode"] == "medium":
        continue_line += 2
    max_call = 0.30 if profile["label"] != "aggressive" else 0.22
    if features["stack"]["mode"] == "medium":
        max_call = min(max_call, 0.28)
    if owed and owed <= pot * 0.18 and score >= continue_line - 12:
        return {"action": "call"}
    if owed and score >= continue_line and owed <= pot * max_call:
        return {"action": "call"}
    spec_cap = 0.16 if features["stack"]["mode"] == "medium" else 0.22
    if owed and speculative and owed <= pot * spec_cap:
        return {"action": "call"}
    broadwayish = high >= 12 and low >= 9 or high == 14 and low >= 5
    if owed and owed <= pot * 0.14 and (pair or suited or broadwayish):
        return {"action": "call"}
    if state["can_check"]:
        return {"action": "check"}
    return {"action": "fold"}


def postflop_policy(state, features):
    owed = state["amount_owed"]
    pot = max(1, state["pot"])
    equity = features["equity"]
    profile = features["profile"]
    texture = features["texture"]
    price = features["pot_price"]["price"]
    position = features["position"]
    opponents = features["opponents"]
    archetypes = features["live_archetypes"]
    bettor = features["bettor_archetype"]
    station_field = "station" in archetypes
    loose_field = any(archetype in ("station", "maniac") for archetype in archetypes)
    tight_field = bool(archetypes) and all(archetype in ("nit", "tag") for archetype in archetypes)
    margin = CONFIG["call_margin"] + CONFIG["multiway_margin"] * max(0, opponents - 1)
    if profile["label"] == "aggressive":
        margin += CONFIG["aggro_tighten"] / 100.0
    if bettor == "maniac":
        margin -= 0.045
    elif bettor == "station":
        margin -= 0.020
    elif bettor == "nit":
        margin += 0.045
    if texture["wet"] and opponents >= 3:
        margin += 0.025
    if texture["board_danger"] and not texture["has_pair"]:
        margin += CONFIG["danger_extra_margin"]
    if state["street"] == "river" and not texture["has_pair"]:
        margin += CONFIG["river_extra_margin"]
    if owed > state["your_stack"] * 0.34:
        margin += CONFIG["large_bet_extra_margin"]
    if owed and owed <= pot * 0.24 and state["street"] != "river":
        margin -= CONFIG["cheap_call_margin_discount"]

    if owed == 0:
        value_line = CONFIG["value_equity"]
        value_fraction = CONFIG["value_bet_fraction"]
        if station_field:
            value_line -= 0.09
            value_fraction = 0.50
        elif loose_field:
            value_line -= 0.06
            value_fraction = 0.56
        elif tight_field:
            value_line += 0.02
        if equity >= value_line or texture["has_pair"] and equity >= value_line - 0.10:
            return {"action": "raise", "amount": _bet_to(state, value_fraction)}
        can_pressure = position == "late" and opponents <= 2 and features["street_aggression"] == 0
        if can_pressure and (texture["flush_draw"] or texture["straight_draw"] or equity >= 0.42):
            bluff_frequency = CONFIG["late_bluff_frequency"]
            if station_field or loose_field:
                bluff_frequency = 0.0
            elif tight_field:
                bluff_frequency = min(0.36, bluff_frequency + 0.12)
            if features["fold_equity"] * pot > (1 - features["fold_equity"]) * max(1, int(pot * CONFIG["pressure_bet_fraction"])) and random.random() < bluff_frequency:
                return {"action": "raise", "amount": _bet_to(state, CONFIG["pressure_bet_fraction"])}
        return {"action": "check"}

    raise_line = CONFIG["raise_equity"] + 0.03
    if station_field:
        raise_line -= 0.08
    elif loose_field:
        raise_line -= 0.05
    if bettor == "maniac":
        raise_line += 0.08
    elif bettor == "nit":
        raise_line += 0.03
    if equity >= raise_line and owed <= state["your_stack"] * 0.38:
        return {"action": "raise", "amount": _bet_to(state, CONFIG["raise_bet_fraction"])}
    if (texture["flush_draw"] or texture["straight_draw"]) and position == "late" and owed <= pot * 0.20:
        draw_raise_frequency = CONFIG["postflop_draw_raise_frequency"]
        if loose_field:
            draw_raise_frequency = 0.0
        elif tight_field:
            draw_raise_frequency = min(0.32, draw_raise_frequency + 0.08)
        if features["fold_equity"] * pot > (1 - features["fold_equity"]) * max(1, owed) and random.random() < draw_raise_frequency:
            return {"action": "raise", "amount": _bet_to(state, CONFIG["pressure_bet_fraction"])}
    if owed <= pot * 0.24 and state["street"] != "river" and (texture["has_pair"] or texture["flush_draw"] or texture["straight_draw"]):
        return {"action": "call"}
    if owed <= pot * 0.14 and state["street"] == "flop" and equity >= 0.30:
        return {"action": "call"}
    if equity >= price + margin:
        return {"action": "call"}
    return {"action": "fold"}


def decide(state):
    features = extract_features(state)
    if short_stack_policy_applies(features):
        return short_stack_action(state, features)
    if state["street"] == "preflop":
        return preflop_policy(state, features)
    return postflop_policy(state, features)
